# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiplies by two!
#'
#' @param x number
#' @return twice as much as `x`
#'
#' @export
times_two <- function(x) {
  .Call("_extreme_trawl_times_two", PACKAGE = "extreme.trawl", x)
}

#' Computes cross moment in trawl gamma-exponential mixture
#'
#' @param xs Grid to integrate on.
#' @param delta Grid mesh size
#' @param beta GPD scale parameter in the sense of Noven et al.
#' @param b_oh - alpha * mu(A inter A_h) / mu  (A)
#' @param b_o_exc_h - alpha * mu(A excl. A_h) / mu  (A)
#' @return Cross moment value
#'
#' @export
cross_moment <- function(xs, delta, beta, b_oh, b_o_exc_h) {
  .Call("_extreme_trawl_cross_moment", PACKAGE = "extreme.trawl", xs, delta, beta, b_oh, b_o_exc_h)
}

#' Computes first moment in trawl gamma-exponential mixture
#'
#' @param xs Grid to integrate on.
#' @param delta Grid mesh size
#' @param beta GPD scale parameter in the sense of Noven et al.
#' @param b_oh - alpha * mu(A inter A_h) / mu  (A)
#' @param b_o_exc_h - alpha * mu(A excl. A_h) / mu  (A)
#' @return First moment value
#'
#' @export
first_moment <- function(xs, delta, beta, b_oh, b_o_exc_h) {
  .Call("_extreme_trawl_first_moment", PACKAGE = "extreme.trawl", xs, delta, beta, b_oh, b_o_exc_h)
}

#' Computes square moment in trawl gamma-exponential mixture
#'
#' @param xs Grid to integrate on.
#' @param delta Grid mesh size
#' @param beta GPD scale parameter in the sense of Noven et al.
#' @param b_oh - alpha * mu(A inter A_h) / mu  (A)
#' @param b_o_exc_h - alpha * mu(A excl. A_h) / mu  (A)
#' @return Square moment value
#'
#' @export
square_moment <- function(xs, delta, beta, b_oh, b_o_exc_h) {
  .Call("_extreme_trawl_square_moment", PACKAGE = "extreme.trawl", xs, delta, beta, b_oh, b_o_exc_h)
}

#' Cpp pairwise likelihood 0-0 (zero-zero).
#'
#' @param alpha Gamma shape.
#' @param beta Gamma rate.
#' @param kappa Exceedance controlling parameter.
#' @param b_1 B one.
#' @param b_2 B two.
#' @param b_3 B three.
#' @return pairwise likelihood 0-0 (zero-zero).
cpp_case_zero_zero <- function(alpha, beta, kappa, b_1, b_2, b_3) {
  .Call("_extreme_trawl_cpp_case_zero_zero", PACKAGE = "extreme.trawl", alpha, beta, kappa, b_1, b_2, b_3)
}

#' Cpp pairwise likelihood 1-0 (one-zero).
#'
#' @param xs Data.
#' @param alpha Gamma shape.
#' @param beta Gamma rate.
#' @param kappa Exceedance controlling parameter.
#' @param b_1 B one.
#' @param b_2 B two.
#' @param b_3 B three.
#' @return pairwise likelihood 1-0 (one-zero).
cpp_case_one_zero <- function(xs, alpha, beta, kappa, b_1, b_2, b_3) {
  .Call("_extreme_trawl_cpp_case_one_zero", PACKAGE = "extreme.trawl", xs, alpha, beta, kappa, b_1, b_2, b_3)
}

#' Cpp pairwise likelihood 1-1 (one-one).
#'
#' @param xs Data.
#' @param alpha Gamma shape.
#' @param beta Gamma rate.
#' @param kappa Exceedance controlling parameter.
#' @param b_1 B one.
#' @param b_2 B two.
#' @param b_3 B three.
#' @return pairwise likelihood 1-1 (one-one).
cpp_case_one_one <- function(xs, alpha, beta, kappa, b_1, b_2, b_3) {
  .Call("_extreme_trawl_cpp_case_one_one", PACKAGE = "extreme.trawl", xs, alpha, beta, kappa, b_1, b_2, b_3)
}

#' Cpp pairwise likelihood separator that chooses which routine to use.
#'
#' @param xs Data.
#' @param alpha Gamma shape.
#' @param beta Gamma rate.
#' @param kappa Exceedance controlling parameter.
#' @param b_1 B one.
#' @param b_2 B two.
#' @param b_3 B three.
#' @return PL likelihood values for `xs`.
cpp_case_separator <- function(xs, alpha, beta, kappa, b_1, b_2, b_3) {
  .Call("_extreme_trawl_cpp_case_separator", PACKAGE = "extreme.trawl", xs, alpha, beta, kappa, b_1, b_2, b_3)
}
