# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

times_two <- function(x) {
  .Call("_extreme_trawl_times_two", PACKAGE = "extreme.trawl", x)
}

#' Computes cross moment in trawl gamma-exponential mixture
#'
#' @param xs Grid to integrate on.
#' @param delta Grid mesh size
#' @param beta GPD scale parameter in the sense of Noven et al.
#' @param b_oh - alpha * mu(A inter A_h) / mu  (A)
#' @param b_o_exc_h - alpha * mu(A excl. A_h) / mu  (A)
#'
#' @export
cross_moment <- function(xs, delta, beta, b_oh, b_o_exc_h) {
  .Call("_extreme_trawl_cross_moment", PACKAGE = "extreme.trawl", xs, delta, beta, b_oh, b_o_exc_h)
}

first_moment <- function(xs, delta, beta, b_oh, b_o_exc_h) {
  .Call("_extreme_trawl_first_moment", PACKAGE = "extreme.trawl", xs, delta, beta, b_oh, b_o_exc_h)
}

square_moment <- function(xs, delta, beta, b_oh, b_o_exc_h) {
  .Call("_extreme_trawl_square_moment", PACKAGE = "extreme.trawl", xs, delta, beta, b_oh, b_o_exc_h)
}

#' @export
cpp_case_zero_zero <- function(alpha, beta, kappa, b_1, b_2, b_3) {
  .Call("_extreme_trawl_cpp_case_zero_zero", PACKAGE = "extreme.trawl", alpha, beta, kappa, b_1, b_2, b_3)
}

#' @export
cpp_case_one_zero <- function(xs, alpha, beta, kappa, b_1, b_2, b_3) {
  .Call("_extreme_trawl_cpp_case_one_zero", PACKAGE = "extreme.trawl", xs, alpha, beta, kappa, b_1, b_2, b_3)
}

#' @export
cpp_case_one_one <- function(xs, alpha, beta, kappa, b_1, b_2, b_3) {
  .Call("_extreme_trawl_cpp_case_one_one", PACKAGE = "extreme.trawl", xs, alpha, beta, kappa, b_1, b_2, b_3)
}

#' @export
cpp_case_separator <- function(xs, alpha, beta, kappa, b_1, b_2, b_3) {
  .Call("_extreme_trawl_cpp_case_separator", PACKAGE = "extreme.trawl", xs, alpha, beta, kappa, b_1, b_2, b_3)
}
